
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  CFNTableName1:
    Type: String
    Default: cfn-manual-table-flights-1

Resources:
  CFNDatabaseFlights:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId   
      DatabaseInput:
        Name: !Ref AWS::StackName	
        Description: Database to hold tables for power prices

  CFNTableFlights:
    DependsOn: CFNDatabaseFlights
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref AWS::StackName
      TableInput:
        Name: !Ref CFNTableName1
        Description: This table holds the values for power prices from electricityinfo
        TableType: EXTERNAL_TABLE
        Parameters: {"classification": "json"}
        PartitionKeys: []
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
          - Name: ben2201
            Type: double
          - Name: date_time
            Type: string
          - Name: brb0331
            Type: double
          - Name: dob0661
            Type: double
          - Name: hay2201
            Type: double
          - Name: hly2201
            Type: double
          - Name: hwb2201
            Type: double
          - Name: inv2201
            Type: double
          - Name: isl2201
            Type: double
          - Name: ota2201
            Type: double
          - Name: sfd2201
            Type: double
          - Name: stk2201
            Type: double
          - Name: tui1101
            Type: double
          - Name: wkm2201
            Type: double
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: s3://get-power-priceselectrictyinfos3bucket-ej4frh4c7p4b/
          SerdeInfo:
            Parameters:
              field.delim: ","
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
            Parameters: {"paths": "BEN2201,BRB0331,DOB0661,HAY2201,HLY2201,HWB2201,INV2201,ISL2201,OTA2201,SFD2201,STK2201,TUI1101,WKM2201,date_time"}